#pragma once

#define MAX_EVENTS 10

enum game_events
{
	RED_KILLED = 47,
	GREEN_KILLED = 57,
	BLUE_KILLED = 67,
	WHITE_KILLED=77,

	RED_CONNECTED = 48,
	GREEN_CONNECTED = 58,
	BLUE_CONNECTED = 68,
	WHITE_CONNECTED = 78,

	RED_DISCONNECTED = 49,
	GREEN_DISCONNECTED = 59,
	BLUE_DISCONNECTED = 69,
	WHITE_DISCONNECTED = 79,

	MOVE_PASS = 254,
	MOVE_FAIL = 253,
};
